package com.shubhi.bre_lookup_testing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Data_object implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Data_object() {
    }




}